# Generated by Django 5.2.6 on 2025-09-20 14:52

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the book title', max_length=200)),
                ('author', models.CharField(help_text="Enter the author's name", max_length=200)),
                ('isbn', models.CharField(help_text='13 or 10 digit ISBN number', max_length=17, unique=True)),
                ('publication_date', models.DateField(help_text='Date when the book was published')),
                ('description', models.TextField(blank=True, help_text='Brief description of the book', max_length=2000)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci_fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('history', 'History'), ('self_help', 'Self Help'), ('business', 'Business'), ('poetry', 'Poetry'), ('drama', 'Drama'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('young_adult', 'Young Adult'), ('children', 'Children'), ('other', 'Other')], default='other', help_text='Select the book genre', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cover_image', models.ImageField(blank=True, help_text='Upload book cover image', null=True, upload_to=books.models.book_cover_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
    ]
